<?php
$sugar_config_si = array (
    'default_currency_iso4217' => 'DEFAULT_CURRENCY_ISO4217', //'USD'
    'default_currency_name' => 'DEFAULT_CURRENCY_NAME', //'US Dollars'
    'default_currency_significant_digits' => DEFAULT_CURRENCY_SIGNIFICANT_DIGITS, //'2'
    'default_currency_symbol' => 'DEFAULT_CURRENCY_SYMBOL', //'$'
    'default_date_format' => 'DEFAULT_DATE_FORMAT', //'Y-m-d'
    'default_decimal_seperator' => 'DEFAULT_DECIMAL_SEPERATOR', //'.'
    'default_export_charset' => 'DEFAULT_EXPORT_CHARSET', //'ISO-8859-1'
    'default_language' => 'DEFAULT_LANGUAGE', //'en_us'
    'default_locale_name_format' => 'DEFAULT_LOCALE_NAME_FORMAT', //'s f l'
    'default_number_grouping_seperator' => 'DEFAULT_NUMBER_GROUPING_SEPERATOR', //','
    'default_time_format' => 'DEFAULT_TIME_FORMAT', //'H:i'
    'export_delimiter' => 'EXPORT_DELIMITER', //','
    'setup_db_admin_password' => 'SETUP_DB_ADMIN_PASSWORD', //'suitecrm' // DATABASE ADMIN USER PASSWORD
    'setup_db_admin_user_name' => 'SETUP_DB_ADMIN_USER_NAME', //'suitecrm' // DATABASE ADMIN USER NAME
    'setup_db_create_database' => 'SETUP_DB_CREATE_DATABASE', //'1' // CREATE THE DATABASE IF IT DOESN'T EXIST
    'setup_db_drop_tables' => 'SETUP_DB_DROP_TABLES', //'1' // DROP THE TABLES IF THEY EXIST
    'setup_db_sugarsales_password' => 'SETUP_DB_SUGARSALES_PASSWORD', //'root' // THE DATABASE PASSWORD TO USE AFTER INSTALLATION TO CONNECT
    'setup_db_sugarsales_password_retype' => 'SETUP_DB_SUGARSALES_PASSWORD_RETYPE', //'root' // AGAIN
    'setup_db_sugarsales_user' => 'SETUP_DB_SUGARSALES_USER', //'root' // THE DATABASE USER TO USE AFTER INSTALLATION TO CONNECT
    'setup_db_type' => 'SETUP_DB_TYPE', //'mysql' // OR OTHER DATABASE TYPE (ibm_db2, etc)
    'setup_db_host_name' => 'SETUP_DB_HOST_NAME', //'db', // DATABASE HOST LOCATION
    'setup_db_port_num' => SETUP_DB_PORT_NUM, //'3306' // DATABASE PORT
    'setup_db_create_sugarsales_user' => SETUP_DB_CREATE_SUGARSALES_USER, //0 // CREATE THE DATABASE USER TO USE AFTER INSTALLATION
    'setup_db_database_name' => 'SETUP_DB_DATABASE_NAME', //'suitecrm' // THE DATABASE NAME
    'setup_db_pop_demo_data' => SETUP_DB_POP_DEMO_DATA, //0 // (0 or 1) POPULATE DEMO DATA
    'dbUSRData' => 'DBUSRDATA', //'provide'
    'demoData' => 'DEMODATA', //'yes' // (yes or no) POPULATE DEMO DATA
    'setup_license_key' => 'SETUP_LICENSE_KEY', //'INSERT_YOUR_LICENSE_KEY_HERE', // License Key
    'setup_site_admin_user_name'=> 'SETUP_SITE_ADMIN_USER_NAME', //'admin' // SUGAR ADMIN USER NAME
    'setup_site_admin_password_retype' => 'SETUP_SITE_ADMIN_PASSWORD_RETYPE', //admin
    'setup_site_admin_password' => 'SETUP_SITE_ADMIN_PASSWORD', //'admin' // SUGAR ADMIN PASSWORD
    'setup_site_url' => 'SETUP_SITE_URL', //'http://localhost/', // PATH TO SUGAR INSTANCE VIA URL
    'setup_system_name' => SETUP_SYSTEM_NAME, //'*** My SugarCRM Instance *** '.date('Y-m-d H:i'), // INSTANCE NAME
    'setup_fts_type' => 'SETUP_FTS_TYPE', //'Elastic', // TYPE OF FULL TEXT SEARCH
    'setup_fts_host' => 'SETUP_FTS_HOST', //'localhost', // HOST FOR FULL TEXT SEARCH
    'setup_fts_port' => SETUP_FTS_PORT //'9200', // PORT NUMBER FOR FULL TEXT SEARCH
);
?>