version: '3.7'
services:
  db:
    image: 'mysql:5'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_DATABASE=suitecrm
      - MYSQL_PASSWORD=suitecrm
    ports:
      - "3306:3306"
    volumes:
      - './suitecrm_data_db:/var/lib/mysql'

  joomla:
    image: joomla
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: suitecrm

  suitecrm:
    image: 'senzil/suitecrm:dev'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        php_version: apache
        suitecrm_version: 7.10.11
    restart: always
    environment:
      - SETUP_DB_HOST_NAME=db
      - SETUP_DB_SUGARSALES_USER=suitecrm
      - SETUP_DB_SUGARSALES_PASSWORD=suitecrm
      - SETUP_DB_SUGARSALES_PASSWORD_RETYPE=suitecrm
      - SETUP_DB_ADMIN_PASSWORD=suitecrm
      - SILENT_INSTALL=true
    ports:
      - '80:80'
    volumes:
      - './suitecrm_data/upload:/var/www/html/upload'
      - '${PWD}/php.suitecrm.ini:/usr/local/etc/php/conf.d/php.suitecrm.ini'
    depends_on:
      - db
      - joomla
