version: '3.7'
services:
  db:
    image: 'mysql:5'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_DATABASE=suitecrm
      - MYSQL_PASSWORD=suitecrm
    ports:
      - "3306:3306"
    volumes:
      - './suitecrm_data_db_db:/var/lib/mysql'

  joomla:
    image: joomla
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: suitecrm

  suitecrm:
    image: 'senzil/suitecrm'
    restart: always
    environment:
      - SILENT_INSTALL=FALSE
    ports:
      - '80:80'
    volumes:
      - './suitecrm_data/upload:/var/www/html/upload'
    depends_on:
      - db
      - joomla
